In [7]:
import numpy as np


# 1.Array Arithmatic Operator

In [13]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])


In [14]:
arr1

array([1, 2, 3, 4, 5])

In [15]:
arr2

array([ 6,  7,  8,  9, 10])

In [16]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [18]:
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [19]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [20]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [21]:
arr1 // arr2 

array([0, 0, 0, 0, 0])

In [22]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [23]:
arr1.shape ==arr.shape

False

In [24]:
arr1.shape ==arr2.shape

True

# Broadcasting

In [30]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [31]:
arr1 + 5

array([ 6,  7,  8,  9, 10])

# Array and Sclar

In [33]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [34]:
arr1 - 5

array([-4, -3, -2, -1,  0])

In [35]:
arr1 * 5

array([ 5, 10, 15, 20, 25])

In [36]:
arr1 / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

# Shape of Array

In [38]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr2

array([ 6,  7,  8,  9, 10])

In [42]:
arr.shape

(9,)

In [41]:
arr2.shape

(5,)

# Row-Wise Broadcasting