In [2]:
import numpy as np

arr = np.array([[ 1, 2, 3, 4, 5],
               [ 6, 7, 8, 9, 10],
               [ 11, 12, 13, 14, 15],
               [ 16, 17, 18, 19, 20],
               [ 21, 22, 23, 24, 25],
               [ 26, 27, 28, 29, 30]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [3]:
arr[0]

array([1, 2, 3, 4, 5])

In [4]:
arr[5]

array([26, 27, 28, 29, 30])

In [5]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [9]:
arr[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
arr[-3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[:,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [12]:
arr[:-2:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
arr[1:4,2:5]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [14]:
arr[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [16]:
arr[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [17]:
arr[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25],
       [26, 28, 30]])

In [18]:
arr[-1:,-2:]

array([[29, 30]])

In [19]:
arr[-3:,-2:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [20]:
arr[:4,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [21]:
arr[::-1]

array([[26, 27, 28, 29, 30],
       [21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [22]:
arr[:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21],
       [30, 29, 28, 27, 26]])

In [23]:
arr[::-1,::-1]

array([[30, 29, 28, 27, 26],
       [25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [24]:
arr[2:4,1:4]

array([[12, 13, 14],
       [17, 18, 19]])